// Tarjetas KPI del Panel de inicio.
// valor y tendencia son placeholders hasta conectar la fuente real.
// sparklineEjemplo: datos de muestra para la mini línea de tendencia (decorativa).

export const metricas = [
  {
    id: 'plantel-activo',
    titulo: 'Plantel Activo',
    // TODO: conectar a tabla Supabase o hoja Sheets con total de empleados activos
    valor: '—',
    descripcion: 'empleados',
    tendencia: null,
    color: '#1a4a7a',
    icono: 'personas',
    sparklineEjemplo: null,
    destino: { modulo: 'plantel', submodulo: 'resumen' },
  },
  {
    id: 'ausentismo',
    titulo: 'Ausentismo',
    valor: '—',
    descripcion: 'último período cargado',
    color: '#e67e22',
    icono: 'calendario',
    destino: { modulo: 'presentismo', submodulo: 'indicadores' },
  },
  {
    id: 'solicitudes-pendientes',
    titulo: 'Solicitudes Pend.',
    valor: '—',
    descripcion: 'permisos por autorizar',
    color: '#8e44ad',
    icono: 'documento',
    destino: { modulo: 'permisos', submodulo: 'pendientes' },
  },
  {
    id: 'ingresos-mes',
    titulo: 'Ingresos este mes',
    valor: '—',
    descripcion: 'altas del mes en curso',
    color: '#27ae60',
    icono: 'ingreso',
    destino: { modulo: 'plantel', submodulo: 'listado' },
  },
  {
    id: 'presentismo-reciente',
    titulo: 'Presentismo reciente',
    valor: '—',
    descripcion: 'último sábado registrado',
    color: '#7c3aed',
    icono: 'calendario',
    destino: { modulo: 'sabados-feriados', submodulo: 'resumen' },
  },
  {
    id: 'vencimientos-alerta',
    titulo: 'Vencimientos en alerta',
    valor: '—',
    descripcion: 'vencidos o dentro del preaviso',
    color: '#dc2626',
    icono: 'alerta',
    destino: { modulo: 'vencimientos', submodulo: 'resumen' },
  },
  {
    id: 'postulantes-mes',
    titulo: 'Postulantes este mes',
    valor: '—',
    descripcion: 'nuevas postulaciones del mes',
    color: '#0284c7',
    icono: 'personas',
    destino: { modulo: 'postulantes', submodulo: 'postulantes' },
  },
  {
    id: 'preseleccionados-mes',
    titulo: 'Preseleccionados del mes',
    valor: '—',
    descripcion: 'candidatos activos revisados',
    color: '#16a34a',
    icono: 'ingreso',
    destino: { modulo: 'postulantes', submodulo: 'preseleccion' },
  },
];
